// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://butfhcmfdkiucemoulgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1dGZoY21mZGtpdWNlbW91bGdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MTE2ODIsImV4cCI6MjA1MzE4NzY4Mn0.xVnL3VJYvslfcLE39Z-X3mKvSJBPgrIAelZEoim6bD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);